# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nilay's Blog
email: nilayshrivastava1729@gmail.com
description: Musings of a Math addict
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://euler16.github.io" # the base hostname & protocol for your site
twitter_username: NilayShri
github_username:  euler16
facebook_username: nilay.shrivastava.1729
linkedin_username: nilayshrivastava1729
paginate: 6

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
highlighter: rouge
